### ISSUE TITLE
Normalize MediaBox and TrimBox rectangles before tiling pages

### ISSUE THREAD

**Issue by ahsatan** [cfcurtis/pdfstitcher#146]
Pattern: Eldenberry Blossoms Berry Booties (Adult)

When I attempt to trim .5" from each side, the left and right appear to trim correctly but top and bottom only cumulatively trim one edge.  The resulting pdf looks the same when only trimming top by .5", only trimming bottom by .5", or trimming both by .5".

The designer is updating her pattern files so I'm not needing a fix specifically to use this but I wanted to file the issue so hopefully it provides info to track down whatever is causing trim weirdness here!  Overlap does not work btw as I believe it's been turned into an image and not vector lines anymore so the whitespace overlaps and hides pattern lines.

**Comment by cfcurtis** [comment]
Thanks for the report! I've edited your comment to remove the links to protect the pattern designer's IP, but they were quite useful. The problem is that this PDF has a strangely defined MediaBox, and PDFStitcher isn't handling it properly. Right now I assume that the page is defined with coordinates [lower x, lower y, upper x, upper y], but this document is instead [lower x, upper y, upper x, lower y].

Relevant section of the PDF reference for reference:

![image](https://user-images.githubusercontent.com/282731/165010798-253eb260-bdd7-4057-a1f0-4fb49ce5e0cb.png)
