### ISSUE TITLE
Failure on opening a pdf

### ISSUE THREAD

**Issue by Sewing-left-0field** [cfcurtis/pdfstitcher#162]
I'm using a macbook air M1 running ventura.

When I try to open a pdf using pdfsticther I can an error.

Opening /Users/paulhoward/Dropbox/Sewing Patterns/PDF patterns Downloaded/EM_Adult's_Going_Home_Sweater_Pattern-Final-Projector.pdf
Traceback (most recent call last):
  File "pdfstitcher/ui/main_frame.py", line 408, in on_open
  File "pdfstitcher/ui/main_frame.py", line 418, in load_file
  File "pikepdf/_methods.py", line 800, in open
pikepdf._qpdf.PdfError: /Users/paulhoward/Dropbox/Sewing Patterns/PDF patterns Downloaded/EM_Adult's_Going_Home_Sweater_Pattern-Final-Projector.pdf: unable to find trailer dictionary while recovering damaged file.

This happens regardless of the file I try to open but only when the file resides on dropbox. If I put the file on the desktop it opens fine.

**Comment by cfcurtis** [comment]
Thanks for the report! It sounds like some kind of strange interaction between Dropbox, macOS, and the PDF parsing library (QPDF) - for some reason QPDF thinks that the file is corrupted when it's in Dropbox. Does it open correctly in other PDF software?

I will update the QPDF version in my next (very overdue!) release, but if the problem persists then I would recommend opening an issue with [QPDF](https://github.com/qpdf/qpdf). It may very well be a Dropbox problem instead, but that's harder to deal with since it's not open source.
